{% set name = "geomatics" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8645ff94e0dcb0b18fb3cc0c94311ae9f7ca2f0386479e297515fcf3629cefe1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rasterio
    - rasterstats
    - netCDF4
    - requests
    - python-dateutil
    - numpy
    - pandas
    - pyshp
    - pygrib

test:
  imports:
    - geomatics


about:
  home: https://github.com/rileyhales/geomatics
  summary: GIS tools developed by Riley Hales for the BYU Hydroinformatics Lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geomatics.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
