{% set name = "geomatics" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff95469f2d9e989fb15029b206bf81e3874f438bb292a9bce9caf022f4247159

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rasterio
    - rasterstats
    - xarray
    - h5py
    - netcdf4
    - eccodes
    - cfgrib
    - python-dateutil
    - numpy
    - pandas
    - requests
    - pyshp
    - affine
    - pillow
    - geopandas
    - pygrib

test:
  imports:
    - geomatics


about:
  home: https://github.com/rileyhales/geomatics
  summary: GIS tools in pure python developed by Riley Hales as part of a Master's Thesis at Brigham Young University.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geomatics.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
